export type StarshipItem = {
  MGLT: String;
  cargo_capacity: Number;
  consumables: String;
  cost_in_credits: Number;
  created: Date;
  crew: Number;
  edited: Date;
  hyperdrive_rating: Number;
  length: Number;
  manufacturer: String;
  max_atmosphering_speed: String;
  model: String;
  name: String;
  passengers: Number;
  films: String[];
  pilots: String[];
  starship_class: String;
  url: String;
};
