export type StarshipItem = {
  MGLT: String;
  cargo_capacity: String;
  consumables: String;
  cost_in_credits: String;
  created: Date;
  crew: String;
  edited: Date;
  hyperdrive_rating: String;
  length: String;
  manufacturer: String;
  max_atmosphering_speed: String;
  model: String;
  name: String;
  passengers: String;
  films: String[];
  pilots: String[];
  starship_class: String;
  url: String;
};
